#!/usr/bin/env bash
#set -x
echo running Vagrant using salt-bevy definitions
PWD="$(pwd -P)"
export VAGRANT_PWD=$PWD
SCRIPTPATH="$( cd "$(dirname "$0")/../salt-bevy" ; pwd -P )"
echo from $SCRIPTPATH
export VAGRANT_CWD=$SCRIPTPATH
arg2="$2"
if [ "$arg2" == "generic_no_salt" ]
then
  arg2="generic"
else
  VAGRANT_SALT='true'
fi
if [ "$arg2" == "generic" ]
then
  export GENERIC='true'
  if [ "$1" == "up" ]
  then
    export NODE_ADDRESS=$4
    export NODE_MEMORY=$5
    export NODE_BOX=$6
    echo vagrant $1 $3 $7 $8
    /usr/bin/env vagrant $1 $3 $7 $8
  else
    echo vagrant $1 $3 $4 $5 $6 $7 $8
    /usr/bin/env vagrant $1 $3 $4 $5 $6 $7 $8
  fi
  NODE_ADDRESS=
  NODE_BOX=
  NODE_MEMORY=
  VAGRANT_SALT=
else
  GENERIC=
  echo vagrant "$@"
  /usr/bin/env vagrant "$@"
fi
GENERIC=
VAGRANT_CWD=
VAGRANT_PWD=
