#!/usr/bin/env bash
echo running Vagrant using salt-bevy definitions
PWD="$(pwd -P)"
export VAGRANT_PWD=$PWD
SCRIPTPATH="$( cd "$(dirname "$0")/../salt-bevy" ; pwd -P )"
echo from $SCRIPTPATH
export VAGRANT_CWD=$SCRIPTPATH
arg1="$1"
if [ "$arg1" == "--no-salt" ]
then
  shift 1
  VAGRANT_SALT=
else
  export VAGRANT_SALT='true'
fi
pushd $SCRIPTPATH
if [ "$2" == "generic" ]
then
  export GENERIC='true'
  if [ "$1" == "up" ]
  then
    if [ "$4" > " " ]; then export NODE_ADDRESS=$4 ; fi
    if [ "$5" > " " ]; then export NODE_MEMORY=$5 ; fi
    if [ "$6" > " " ]; then export NODE_BOX=$6 ; fi
    echo vagrant $1 $3 $7 $8
    /usr/bin/env vagrant $1 $3 $7 $8
  else
    echo vagrant $1 $3 $4 $5 $6 $7 $8
    /usr/bin/env vagrant $1 $3 $4 $5 $6 $7 $8
  fi
  NODE_ADDRESS=
  NODE_BOX=
  NODE_MEMORY=
  VAGRANT_SALT=
else
  GENERIC=
  echo vagrant "$@"
  /usr/bin/env vagrant "$@"
fi
GENERIC=
VAGRANT_CWD=
VAGRANT_PWD=
popd
